version: '3'
services:
  datastore:
    image: postgres
    env_file: .env.pg
    ports:
      - "9393:5432"
    
  api:
    build:
      context: .
    depends_on: 
      - datastore
    environment: 
      - DB_HOST=datastore
      - DB_PORT=5432
      - DB_USER=username
      - DB_PASS=password
      - DB_NAME=regin
      - PORT=5000
      - JWT_SECRET=my little secret
      - COOKIE_SECRET=my little secret

  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./infrastructure/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/www/html"
    depends_on: 
      - api